# this is simply copied over from config/config_designers.yml

# project definitions
project: mydoc_designers
audience: designers
product: doc
platform: all
version: all
output: web
destination: ../doc_outputs/mydoc/designers
topnav_title: LearnOpenGL Türkçe Çeviri
homepage_title: 
site_title: LearnOpenGL Türkçe Çeviri
project_folder: mydoc
company_name: 
footer_image_location:
github_editme_path: 
disqus_shortname: idrbwjekyll
# variables



theme_file: theme-green.css
pdf_file_name: 

# the algolia entries here are experimental only.

#gems:
#  - algoliasearch-jekyll
#algolia:
#  application_id: 'HXUBJERYYB'
#  index_name:     'documentation_theme_jekyll_designers'
port: 4009

exclude:
  - _site
  - _drafts
  - configs/
  - doc/mydoc_writers*

# same for all
host: 127.0.0.1
feedback_email: nezihe.sozen@gmail.com

# these settings should work, but they don't seem to apply the right highlighting

highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  hard_wrap: false
  syntax_highlighter: rouge




collections:
  tooltips:
    output: false

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      comments: true
      search: true
  -
    scope:
      path: ""
      type: "tooltips"
    values:
      layout: "page"
      comments: true
      search: true
      tooltip: true

